language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli # 安装hexo

install:
  - hexo -v
  - npm install hexo-search --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-feed --save

#before_script:
#  - git clone https://github.com/ppoffice/hexo-theme-hueman.git themes/hueman # 安装主题插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd public
  - git init
  - git config user.name "yangeren"
  - git config user.email "xiaoyaoyangeren@163.com"
  - git add .
  - git commit -m "Auto deploy from Travis-CI."
  - git push --force --quiet "https://$GH_Token@github.com/$GH_REPO.git" master:master

branches:
  only:
    - myblog

env:
  global:
    - GH_REPO: yangeren/yangeren.github.io
    - secure: "EQSfMBuS3/ayhaIcKcGll1BgbgiQY10PZEpl07KXx0823f0vjfIic0qQm09c7hkie+GsPH9otAqfFxm7oS4uuXZtVF2PWCd38ede8sJ6GJgLDwzCXL/J0mpemHUj4dOkDArQZb9LuQ93DT14qWZbn5pSd7Wb9kd9mCLEKCC4F4TXnaaeWP+p0ILj62C0xZvCE0h84XMYR+2E2lsNbVbUNjSjXLmNun4APWdAu+I0fgFrIPZQt/VxITyEebcDLdZ/VVxqJ0ZzwvqDqdDeopVTAvfjOo24SyOpQFhcJT3Z4JpnqE52nW8WMTPWRuPhho6lAstTWRDDit+lhticRI1WFQbhoE8zH45dBfTYWv2XMe6jKAM36eLS5RInDo50cllUiwMJsl5F8dzrzzMGlu8En8KH78GzpNzzpUx2DXVz4VY5EkIZV++CQHZnwJwiUXIYbNEVQItMvmSPXr38TM1xtvXJ3/44l4khgrjq10PCR9YB1ejOC3um4pIc/llC8DKvqt0Rv/e1BnJXfiwLOKGjtN6hhvZDc08IxOYoZKtPp8exGRSHiKSqzJdT76VsMZFdMUq4sZdfL+kbj5x+/CK7SmeEbvePA2HpOa4PRAvZML5Nsy1NxWWDwhTjvlC00RuQvRl/VepuZozfObVHEH70xL1/M3S/XRP0AMHawxRnR/A="
